name: malkomich
title: Malkomich Tech Blog
description: All boils down to code
tags:
  - software
  - developer
  - backend
  - git
  - java
  - software_architecture
  - CI
  - automation
  - AI
  - python
  - spring
  - devops
  - microservices
  - REST
  - API
  - docker
  - javascript
menu:
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Contact
    url: /contact
disqus_identifier: malkomich
blog_url: /blog
show_hero: true
email: malkomich@gmail.com
