name: Malkomich
title: Malkomich | Tech Blog
description: A tech blog from a tech guy.
tags:
  - blog
  - jekyll
  - tech
  - netlify
email: malkomich@gmail.com
disqus_identifier: malkomich-github-io
show_hero: true
menu:
  - title: Home
    url: /blog
  - title: About
    url: /about
  - title: Contact
    url: /contact
blog_url: /blog
