name: malkomich
title: Malkomich Tech Blog
description: All boils down to code
tags:
  - software
  - developer
  - github
  - java
menu:
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Contact
    url: /contact
disqus_identifier: malkomich-github-io
blog_url: /blog
show_hero: true
email: malkomich@gmail.com
